service: apt-db
#provider:
  name: aws
  runtime: nodejs10.x # set node.js runtime
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: us-east-1

functions: # add 4 functions for CRUD
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: aptlistings 
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: aptlistings/{id} 
          method: get
          cors: true
  getAll:
    handler: handler.getAll 
    events:
     - http:
         path: aptlistings
         method: get
         cors: true
  update:
    handler: handler.update 
    events:
     - http:
         path: aptlistings/{id}
         method: put
         cors: true
  remove:
    handler: handler.remove
    events:
     - http:
         path: aptlistings/{id} 
         method: remove
         cors: true
   getFiltered:
    handler: handler.getFiltered 
    events:
     - http:
         path: aptlistings
         method: get
         cors: true
         

plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation
